
name: Android CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: '1.8'
          - name: Publish to Sonatype
            env:
              NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
              NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
            if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
            run: ./gradlew clean build uploadArchives -PNEXUS_USERNAME="${NEXUS_USERNAME}" -PNEXUS_PASSWORD="${NEXUS_PASSWORD}"